"""add serverd from cache field

Revision ID: d68f0b0eb69e
Revises: 0b7e27af7ec8
Create Date: 2026-05-24 11:58:29.424183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68f0b0eb69e'
down_revision: Union[str, Sequence[str], None] = '0b7e27af7ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust!`` ###
    op.add_column('requests', sa.Column('served_from_cache', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'served_from_cache')
    # ### end Alembic commands ###
