from enum import Enum

class ExceptionCode(str, Enum):
    WEATHER_PROVIDER_ERROR = "WEATHER_PROVIDER_ERROR"
    CITY_NOT_FOUND = "CITY_NOT_FOUND"
    WEATHER_PROVIDER_AUTH_ERROR = "WEATHER_PROVIDER_AUTH_ERROR"
    WEATHER_RESPONSE_FORMAT_ERROR = "WEATHER_RESPONSE_FORMAT_ERROR"
    WEATHER_STORAGE_ERROR = "WEATHER_STORAGE_ERROR"
    INVALID_HISTORY_RANGE = "INVALID_HISTORY_RANGE"

